/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.ChiTietDatHang;
import Model.ChiTietGiaoHang;
import Model.ChiTietHoaDon;
import Model.ChiTietLoaiHang;
import Model.DBQuanLyVatTuNongNghiep;
import Model.GetFieldName;
import Model.GiaMatHang;
import Model.HangHoa;
import Model.HoaDon;
import Model.KhachHang;
import Model.LoaiHang;
import Model.NguonHang;
import Model.NhaCungCap;
import Model.NhanVien;
import Model.PhieuDatHang;
import Model.PhieuGiaoHang;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OP15
 */
public class TrangChu_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TrangSanPham_GUI
     */
    DBQuanLyVatTuNongNghiep db = null;
    NhanVien user;
    public TrangChu_GUI() {
        initComponents();
    }
    public TrangChu_GUI(DBQuanLyVatTuNongNghiep db,NhanVien user) {
        initComponents();
        this.db = db;
        this.user = user;
        DefaultTableModel dtm = new DefaultTableModel(); 
        jTable1.setModel(dtm);
        //db.getNguonHangs().insert(new NguonHang("NCC02","CTLH02",2342344));
//        NguonHang upd = db.getNguonHangs().get(0);
//        upd.setGiaNhap(939);
//        NguonHang moi = new NguonHang("NcC01", "CTLH02", 123);        
//        if(db.getNguonHangs().update(upd))
//            System.out.println("update thành ông");
//        else
//            System.out.println("không thành ông");
        Vector  v = new  Vector();
        v.add("sfdsf");
        v.add("sfdsf");
        v.add("sfdsf");
        v.add("sfdsf");
        v.add("sfdsf");
        v.add("sfdsf");
//        dtm.setDataVector(db.getHoaDons().includes("khachHang"), v);
////        String[] s = {"ThanhTien"};
//        Vector a = db.getChiTietLoaiHangs().includes("chiTietHoaDons");
//        for (Object object : a) {
//            System.out.println(object);
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1544, 692));

        jLabel1.setText("TrangChu");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(717, 717, 717))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(326, 326, 326))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
